version: 2.1
aliases:
  - &only-tagged-releases
    tags:
      only: /[0-9]+(\.[0-9]+)*(-[a-z\d\-.]+)?/
    branches:
      ignore: /.*/
  - &only-untagged
    tags:
      ignore: /.*/
executors:
  python:
    docker:
      - image: circleci/python:3.6.9
orbs:
  docker: circleci/docker@0.5.17
jobs:
  test-format:
    executor: python
    steps:
      - checkout
      - run:
          name: Test format for python
          command: make test-format
  test-lint:
    executor: python
    steps:
      - checkout
      - run:
          name: Test lint for python
          command: make test-lint
  test:
    executor: python
    steps:
      - checkout
      - run:
          name: Run tests
          command: make test
  build-and-push:
    parameters:
      additional-tag:
        type: string
        default: ""
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: uscictdocker/mentorpal-classifier
      - docker/push:
          digest-path: /tmp/digest.txt
          image: uscictdocker/mentorpal-classifier
      - unless:
          condition: <<parameters.additional-tag>>
          steps:
            - run:
                command: |
                  echo "Digest is: $(</tmp/digest.txt)"
      - when:
          condition: <<parameters.additional-tag>>
          steps:
            - docker/push:
                digest-path: /tmp/digest-release.txt
                image: uscictdocker/mentorpal-classifier
                tag: "0.0.1"
            - run:
                command: |
                  echo "Digest is: $(</tmp/digest-release.txt)"
      
workflows:
  test-build-deploy:
    jobs:
      - test-format:
          filters: *only-untagged
      - test-lint:
          filters: *only-untagged
          requires:
            - test-format
      - test:
          filters: *only-untagged
          requires:
            - test-lint
      - approve-build-and-push:
          filters: *only-untagged
          type: approval
          requires:
            - test
      - build-and-push:
          filters: *only-untagged
          requires:
            - approve-build-and-push
  test-build-deploy-release:
    jobs:
      - test-format:
          filters: *only-tagged-releases
      - test-lint:
          filters: *only-tagged-releases
          requires:
            - test-format
      - test:
          filters: *only-tagged-releases
          requires:
            - test-lint
      - build-and-push:
          additional-tag: "0.0.1"
          filters: *only-tagged-releases
          requires:
            - test
