version: 2.1
executors:
  python:
    docker:
      - image: circleci/python:3.6.9
orbs:
  docker: circleci/docker@0.5.17
jobs:
  test-format:
    executor: python
    steps:
      - checkout
      - run:
          name: Test format for python
          command: make test-format
  test-lint:
    executor: python
    steps:
      - checkout
      - run:
          name: Test lint for python
          command: make test-lint
  test:
    executor: python
    steps:
      - checkout
      - run:
          name: Run tests
          command: make test
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: uscictdocker/mentorpal-classifier
      - docker/push:
          digest-path: /tmp/digest.txt
          image: uscictdocker/mentorpal-classifier
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test-format
      - test-lint:
          requires:
            - test-format
      - test:
          requires:
            - test-lint
      - approve-build-and-push:
          type: approval
          requires:
            - test
      - build-and-push:
          requires:
            - approve-build-and-push
